### PR TITLE
fix for kernel 4.19

### PR DESCRIPTION
**Pull request by mabrand**
/var/lib/dkms/rtl88x2bu/5.2.4.4/build/include/wifi.h:1014: error: "IEEE80211_MAX_AMPDU_BUF" redefined [-Werror]
 #define IEEE80211_MAX_AMPDU_BUF 0x40

In file included from /var/lib/dkms/rtl88x2bu/5.2.4.4/build/include/osdep_service_linux.h:86,
                 from /var/lib/dkms/rtl88x2bu/5.2.4.4/build/include/osdep_service.h:42,
                 from /var/lib/dkms/rtl88x2bu/5.2.4.4/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl88x2bu/5.2.4.4/build/core/rtw_ioctl_query.c:17:
./include/linux/ieee80211.h:1442: note: this is the location of the previous definition
 #define IEEE80211_MAX_AMPDU_BUF  0x100

### CODE REVIEW

**Comment by mabrand** [comment]
H Max, In case it's useful to you, this lets the build work on kernel 4.19. Feel free to merge or improve and use in your own work. I do not claim much expertise on kernel drivers. Just hacking to be able to use a network dongle in Ubuntu.

There are additional problems with the 4.20 kernel, not solved here.

BTW, thanks for your work on this driver.

**Comment by MaxG87** [comment]
Thank you very much for your contribution.

Could you link a resource on how you installed Linux 4.19? I am on Debian Testing, but my self-compiled 4.19 does not have a build directory and I do not know how to set one up. I need that because I want at least to compile and test your PR.

Thank you very much again.

**Comment by mabrand** [comment]
I built against Ubuntu's mainline kernels downloaded from here:
    http://kernel.ubuntu.com/~kernel-ppa/mainline/
For 4.19.2 amd64, I install these packages from the v4.19.2 directory:
- linux-headers-4.19.2-041902_4.19.2-041902.201811132032_all.deb
- linux-headers-4.19.2-041902-generic_4.19.2-041902.201811132032_amd64.deb
- linux-image-unsigned-4.19.2-041902-generic_4.19.2-041902.201811132032_amd64.deb
- linux-modules-4.19.2-041902-generic_4.19.2-041902.201811132032_amd64.deb

The build directories are created by the headers packages, and dkms works with them:
- /usr/src/linux-headers-4.19.2-041902
- /usr/src/linux-headers-4.19.2-041902-generic
- /usr/src/rtl88x2bu-5.2.4.4

**Comment by MaxG87** [comment]
Thank you very much. I will try out soon.

**Comment by MaxG87** [comment]
Thank you very much for the contribution. I changed minor issues and applied it to the branch 'fork'.
